DROP TABLE IF EXISTS MOVIES;
CREATE TABLE MOVIES(
	SHOW_ID VARCHAR(255),
	TITLE VARCHAR(255),
	DIRECTOR VARCHAR(255),
	CAST_NAME VARCHAR(255),
	COUNTRY VARCHAR(255),
	DATE_ADDED DATE,
	RELEASE_YEAR INT,
	RATING VARCHAR(50),
	DURATION VARCHAR(255),
	LISTED_IN VARCHAR(255),
	DESCRIPTION VARCHAR(500),
	PRIMARY KEY(SHOW_ID)
);

DROP TABLE IF EXISTS TV_SHOWS;
CREATE TABLE TV_SHOWS(
	SHOW_ID VARCHAR(255),
	TITLE VARCHAR(255),
	DIRECTOR VARCHAR(255),
	CAST_NAME VARCHAR(255),
	COUNTRY VARCHAR(255),
	DATE_ADDED DATE,
	RELEASE_YEAR INT,
	RATING VARCHAR(50),
	DURATION VARCHAR(255),
	LISTED_IN VARCHAR(255),
	DESCRIPTION VARCHAR(500),
	PRIMARY KEY(SHOW_ID)
);